import {
  mdiApi,
  mdiBellOutline,
  mdiBluetooth,
  mdiBug,
  mdiCalendarClock,
  mdiCameraOutline,
  mdiCardTextOutline,
  mdiChartLine,
  mdiCheckboxMarkedCircleOutline,
  mdiChip,
  mdiClockOutline,
  mdiCloudUploadOutline,
  mdiCog,
  mdiConnection,
  mdiCrosshairsGps,
  mdiDialpad,
  mdiEthernet,
  mdiExportVariant,
  mdiFan,
  mdiFingerprint,
  mdiFormatFont,
  mdiFormDropdown,
  mdiFormTextbox,
  mdiGauge,
  mdiGestureTapButton,
  mdiImageMultipleOutline,
  mdiImageOutline,
  mdiImageSyncOutline,
  mdiLan,
  mdiLedOn,
  mdiLightbulbOutline,
  mdiLockOutline,
  mdiMemory,
  mdiMicrophone,
  mdiMicrophoneMessage,
  mdiMonitor,
  mdiMotionSensor,
  mdiNfcVariant,
  mdiNumeric,
  mdiPalette,
  mdiPowerPlug,
  mdiPowerSleep,
  mdiQrcode,
  mdiRadioTower,
  mdiRemote,
  mdiRestartAlert,
  mdiScriptTextOutline,
  mdiSerialPort,
  mdiShapeOutline,
  mdiShieldHomeOutline,
  mdiSpeaker,
  mdiSprinklerVariant,
  mdiSwapHorizontal,
  mdiTextBoxOutline,
  mdiThermostat,
  mdiToggleSwitchOutline,
  mdiUsb,
  mdiValve,
  mdiVolumeHigh,
  mdiVpn,
  mdiWeatherSunny,
  mdiWeb,
  mdiWifi,
  mdiWifiCog,
  mdiWifiLock,
  mdiWindowShutter,
  mdiZigbee,
  mdiZWave,
} from "@mdi/js";
import { registerMdiIcons } from "../../util/register-icons.js";

/**
 * Per-domain leading glyph for navigator rows, so a long Core or
 * Components list can be scanned by shape. Keyed on the YAML domain
 * (``item.key``); the value is ``[registered mdi name, svg path]`` so
 * registration derives from this one map and shared glyphs dedupe.
 * Platform components inherit their domain's glyph (``light``, ``sensor``,
 * …); only top-level keys need an entry, and the niche long tail falls
 * through to {@link FALLBACK}.
 */
const DOMAIN_ICON: Record<string, readonly [string, string]> = {
  // Core infrastructure
  esphome: ["chip", mdiChip],
  wifi: ["wifi", mdiWifi],
  ethernet: ["ethernet", mdiEthernet],
  mdns: ["radio-tower", mdiRadioTower],
  network: ["lan", mdiLan],
  api: ["api", mdiApi],
  ota: ["cloud-upload-outline", mdiCloudUploadOutline],
  dashboard_import: ["cloud-upload-outline", mdiCloudUploadOutline],
  logger: ["card-text-outline", mdiCardTextOutline],
  syslog: ["card-text-outline", mdiCardTextOutline],
  web_server: ["web", mdiWeb],
  http_request: ["web", mdiWeb],
  captive_portal: ["wifi-lock", mdiWifiLock],
  improv_serial: ["wifi-cog", mdiWifiCog],
  esp32_improv: ["wifi-cog", mdiWifiCog],
  mqtt: ["swap-horizontal", mdiSwapHorizontal],
  wireguard: ["vpn", mdiVpn],
  socket: ["connection", mdiConnection],
  udp: ["connection", mdiConnection],
  async_tcp: ["connection", mdiConnection],
  espnow: ["connection", mdiConnection],
  serial_proxy: ["connection", mdiConnection],
  sim800l: ["connection", mdiConnection],
  prometheus: ["chart-line", mdiChartLine],
  statsd: ["chart-line", mdiChartLine],
  runtime_stats: ["chart-line", mdiChartLine],
  time: ["clock-outline", mdiClockOutline],
  sntp: ["clock-outline", mdiClockOutline],
  interval: ["clock-outline", mdiClockOutline],
  script: ["script-text-outline", mdiScriptTextOutline],
  uart: ["serial-port", mdiSerialPort],
  i2c: ["connection", mdiConnection],
  spi: ["connection", mdiConnection],
  modbus: ["connection", mdiConnection],
  modbus_controller: ["connection", mdiConnection],
  modbus_server: ["connection", mdiConnection],

  // Board platforms
  esp32: ["chip", mdiChip],
  esp8266: ["chip", mdiChip],
  rp2040: ["chip", mdiChip],
  bk72xx: ["chip", mdiChip],
  rtl87xx: ["chip", mdiChip],
  ln882x: ["chip", mdiChip],
  libretiny: ["chip", mdiChip],
  nrf52: ["chip", mdiChip],
  host: ["chip", mdiChip],
  esp32_hosted: ["wifi", mdiWifi],

  // Bluetooth family
  esp32_ble: ["bluetooth", mdiBluetooth],
  esp32_ble_tracker: ["bluetooth", mdiBluetooth],
  ble: ["bluetooth", mdiBluetooth],
  bluetooth_proxy: ["bluetooth", mdiBluetooth],
  ble_client: ["bluetooth", mdiBluetooth],
  ble_nus: ["bluetooth", mdiBluetooth],
  esp32_ble_beacon: ["bluetooth", mdiBluetooth],
  esp32_ble_server: ["bluetooth", mdiBluetooth],
  zephyr_ble_server: ["bluetooth", mdiBluetooth],
  rp2040_ble: ["bluetooth", mdiBluetooth],
  exposure_notifications: ["bluetooth", mdiBluetooth],
  airthings_ble: ["bluetooth", mdiBluetooth],
  bedjet: ["bluetooth", mdiBluetooth],
  mopeka_ble: ["bluetooth", mdiBluetooth],
  radon_eye_ble: ["bluetooth", mdiBluetooth],
  ruuvi_ble: ["bluetooth", mdiBluetooth],
  xiaomi_ble: ["bluetooth", mdiBluetooth],
  xiaomi_rtcgq02lm: ["bluetooth", mdiBluetooth],

  // Mesh radios
  zwave_proxy: ["z-wave", mdiZWave],
  zigbee: ["zigbee", mdiZigbee],
  openthread: ["zigbee", mdiZigbee],

  // USB
  usb_host: ["usb", mdiUsb],
  usb_uart: ["usb", mdiUsb],
  usb_cdc_acm: ["usb", mdiUsb],
  tinyusb: ["usb", mdiUsb],

  // Power / memory / lifecycle
  psram: ["memory", mdiMemory],
  preferences: ["memory", mdiMemory],
  power_supply: ["power-plug", mdiPowerPlug],
  esp_ldo: ["power-plug", mdiPowerPlug],
  sy6970: ["power-plug", mdiPowerPlug],
  deep_sleep: ["power-sleep", mdiPowerSleep],
  status_led: ["led-on", mdiLedOn],
  safe_mode: ["restart-alert", mdiRestartAlert],
  factory_reset: ["restart-alert", mdiRestartAlert],
  debug: ["bug", mdiBug],

  // Config / data utilities
  globals: ["cog", mdiCog],
  substitutions: ["cog", mdiCog],
  packages: ["cog", mdiCog],
  external_components: ["cog", mdiCog],
  mapping: ["cog", mdiCog],
  json: ["cog", mdiCog],
  bytebuffer: ["cog", mdiCog],
  split_buffer: ["cog", mdiCog],
  sha256: ["lock-outline", mdiLockOutline],
  hmac_md5: ["lock-outline", mdiLockOutline],
  hmac_sha256: ["lock-outline", mdiLockOutline],

  // Remote / sub-GHz / IR radios
  remote_receiver: ["remote", mdiRemote],
  remote_transmitter: ["remote", mdiRemote],
  cc1101: ["remote", mdiRemote],
  sx126x: ["remote", mdiRemote],
  sx127x: ["remote", mdiRemote],
  lightwaverf: ["remote", mdiRemote],
  rf_bridge: ["remote", mdiRemote],

  // NFC / RFID readers
  pn532: ["nfc-variant", mdiNfcVariant],
  pn532_i2c: ["nfc-variant", mdiNfcVariant],
  pn532_spi: ["nfc-variant", mdiNfcVariant],
  pn7150_i2c: ["nfc-variant", mdiNfcVariant],
  pn7160_i2c: ["nfc-variant", mdiNfcVariant],
  pn7160_spi: ["nfc-variant", mdiNfcVariant],
  rc522_i2c: ["nfc-variant", mdiNfcVariant],
  rc522_spi: ["nfc-variant", mdiNfcVariant],
  rdm6300: ["nfc-variant", mdiNfcVariant],

  // Presence / radar
  ld2410: ["motion-sensor", mdiMotionSensor],
  ld2412: ["motion-sensor", mdiMotionSensor],
  ld2420: ["motion-sensor", mdiMotionSensor],
  ld2450: ["motion-sensor", mdiMotionSensor],
  rd03d: ["motion-sensor", mdiMotionSensor],
  at581x: ["motion-sensor", mdiMotionSensor],
  dfrobot_sen0395: ["motion-sensor", mdiMotionSensor],
  hlk_fm22x: ["motion-sensor", mdiMotionSensor],
  seeed_mr24hpc1: ["motion-sensor", mdiMotionSensor],
  seeed_mr60bha2: ["motion-sensor", mdiMotionSensor],
  seeed_mr60fda2: ["motion-sensor", mdiMotionSensor],

  // Touch / keypad / biometric
  esp32_touch: ["gesture-tap-button", mdiGestureTapButton],
  cap1188: ["gesture-tap-button", mdiGestureTapButton],
  mpr121: ["gesture-tap-button", mdiGestureTapButton],
  ttp229_bsf: ["gesture-tap-button", mdiGestureTapButton],
  ttp229_lsf: ["gesture-tap-button", mdiGestureTapButton],
  matrix_keypad: ["dialpad", mdiDialpad],
  wiegand: ["dialpad", mdiDialpad],
  key_collector: ["dialpad", mdiDialpad],
  fingerprint_grow: ["fingerprint", mdiFingerprint],

  // Audio
  i2s_audio: ["volume-high", mdiVolumeHigh],
  audio: ["volume-high", mdiVolumeHigh],
  audio_file: ["volume-high", mdiVolumeHigh],
  microphone: ["microphone", mdiMicrophone],
  micro_wake_word: ["microphone", mdiMicrophone],
  voice_assistant: ["microphone-message", mdiMicrophoneMessage],
  dfplayer: ["speaker", mdiSpeaker],
  rtttl: ["speaker", mdiSpeaker],

  // LED drivers / strip protocols
  adalight: ["lightbulb-outline", mdiLightbulbOutline],
  wled: ["lightbulb-outline", mdiLightbulbOutline],
  e131: ["lightbulb-outline", mdiLightbulbOutline],
  my9231: ["lightbulb-outline", mdiLightbulbOutline],
  sm16716: ["lightbulb-outline", mdiLightbulbOutline],
  sm2135: ["lightbulb-outline", mdiLightbulbOutline],
  sm2235: ["lightbulb-outline", mdiLightbulbOutline],
  sm2335: ["lightbulb-outline", mdiLightbulbOutline],
  bp1658cj: ["lightbulb-outline", mdiLightbulbOutline],
  bp5758d: ["lightbulb-outline", mdiLightbulbOutline],
  tlc59208f: ["lightbulb-outline", mdiLightbulbOutline],
  tlc5947: ["lightbulb-outline", mdiLightbulbOutline],
  tlc5971: ["lightbulb-outline", mdiLightbulbOutline],
  tm1651: ["lightbulb-outline", mdiLightbulbOutline],

  // ADC / DAC
  adc128s102: ["gauge", mdiGauge],
  ads1115: ["gauge", mdiGauge],
  ads1118: ["gauge", mdiGauge],
  mcp3008: ["gauge", mdiGauge],
  mcp3204: ["gauge", mdiGauge],
  as5600: ["gauge", mdiGauge],
  dac7678: ["export-variant", mdiExportVariant],
  gp8403: ["export-variant", mdiExportVariant],
  mcp4728: ["export-variant", mdiExportVariant],
  mcp4461: ["export-variant", mdiExportVariant],
  pca9685: ["export-variant", mdiExportVariant],
  servo: ["export-variant", mdiExportVariant],
  grove_tb6612fng: ["export-variant", mdiExportVariant],

  // IO / bus expanders, muxes, UART bridges
  mcp23008: ["connection", mdiConnection],
  mcp23016: ["connection", mdiConnection],
  mcp23017: ["connection", mdiConnection],
  mcp23s08: ["connection", mdiConnection],
  mcp23s17: ["connection", mdiConnection],
  pca6416a: ["connection", mdiConnection],
  pca9554: ["connection", mdiConnection],
  pcf8574: ["connection", mdiConnection],
  pi4ioe5v6408: ["connection", mdiConnection],
  xl9535: ["connection", mdiConnection],
  max6956: ["connection", mdiConnection],
  sn74hc165: ["connection", mdiConnection],
  sn74hc595: ["connection", mdiConnection],
  cd74hc4067: ["connection", mdiConnection],
  tca9548a: ["connection", mdiConnection],
  tca9555: ["connection", mdiConnection],
  ch422g: ["connection", mdiConnection],
  ch423: ["connection", mdiConnection],
  sx1509: ["connection", mdiConnection],
  m5stack_8angle: ["connection", mdiConnection],
  i2c_device: ["connection", mdiConnection],
  spi_device: ["connection", mdiConnection],
  vbus: ["connection", mdiConnection],
  tuya: ["connection", mdiConnection],
  wk2132_i2c: ["serial-port", mdiSerialPort],
  wk2132_spi: ["serial-port", mdiSerialPort],
  wk2168_i2c: ["serial-port", mdiSerialPort],
  wk2168_spi: ["serial-port", mdiSerialPort],
  wk2204_i2c: ["serial-port", mdiSerialPort],
  wk2204_spi: ["serial-port", mdiSerialPort],
  wk2212_i2c: ["serial-port", mdiSerialPort],
  wk2212_spi: ["serial-port", mdiSerialPort],

  // Chip / environment / meter sensors
  apds9960: ["gauge", mdiGauge],
  as3935_i2c: ["gauge", mdiGauge],
  as3935_spi: ["gauge", mdiGauge],
  bme680_bsec: ["gauge", mdiGauge],
  bme68x_bsec2_i2c: ["gauge", mdiGauge],
  gdk101: ["gauge", mdiGauge],
  msa3xx: ["gauge", mdiGauge],
  ezo_pmp: ["gauge", mdiGauge],
  daly_bms: ["gauge", mdiGauge],
  pylontech: ["gauge", mdiGauge],
  pipsolar: ["gauge", mdiGauge],
  sun_gtil2: ["gauge", mdiGauge],
  sml: ["gauge", mdiGauge],
  dsmr: ["gauge", mdiGauge],
  teleinfo: ["gauge", mdiGauge],
  dlms_meter: ["gauge", mdiGauge],
  emontx: ["gauge", mdiGauge],
  emc2101: ["fan", mdiFan],
  gps: ["crosshairs-gps", mdiCrosshairsGps],
  sun: ["weather-sunny", mdiWeatherSunny],

  // Climate / heating / irrigation
  opentherm: ["thermostat", mdiThermostat],
  uponor_smatrix: ["thermostat", mdiThermostat],
  micronova: ["thermostat", mdiThermostat],
  sprinkler: ["sprinkler-variant", mdiSprinklerVariant],

  // Component platforms
  sensor: ["gauge", mdiGauge],
  binary_sensor: ["checkbox-marked-circle-outline", mdiCheckboxMarkedCircleOutline],
  text_sensor: ["text-box-outline", mdiTextBoxOutline],
  switch: ["toggle-switch-outline", mdiToggleSwitchOutline],
  light: ["lightbulb-outline", mdiLightbulbOutline],
  output: ["export-variant", mdiExportVariant],
  number: ["numeric", mdiNumeric],
  select: ["form-dropdown", mdiFormDropdown],
  button: ["gesture-tap-button", mdiGestureTapButton],
  fan: ["fan", mdiFan],
  cover: ["window-shutter", mdiWindowShutter],
  climate: ["thermostat", mdiThermostat],
  text: ["form-textbox", mdiFormTextbox],
  lock: ["lock-outline", mdiLockOutline],
  valve: ["valve", mdiValve],
  media_player: ["speaker", mdiSpeaker],
  display: ["monitor", mdiMonitor],
  lvgl: ["monitor", mdiMonitor],
  graphical_display_menu: ["monitor", mdiMonitor],
  lcd_menu: ["monitor", mdiMonitor],
  datetime: ["calendar-clock", mdiCalendarClock],
  camera: ["camera-outline", mdiCameraOutline],
  esp32_camera: ["camera-outline", mdiCameraOutline],
  esp32_camera_web_server: ["camera-outline", mdiCameraOutline],
  camera_encoder: ["camera-outline", mdiCameraOutline],
  event: ["bell-outline", mdiBellOutline],
  alarm_control_panel: ["shield-home-outline", mdiShieldHomeOutline],

  // Graphics
  graph: ["chart-line", mdiChartLine],
  color: ["palette", mdiPalette],
  qr_code: ["qrcode", mdiQrcode],
  font: ["format-font", mdiFormatFont],
  image: ["image-outline", mdiImageOutline],
  online_image: ["image-sync-outline", mdiImageSyncOutline],
  animation: ["image-multiple-outline", mdiImageMultipleOutline],
};

/** Neutral glyph for any domain not in {@link DOMAIN_ICON}. */
const FALLBACK: readonly [string, string] = ["shape-outline", mdiShapeOutline];

registerMdiIcons(Object.fromEntries([...Object.values(DOMAIN_ICON), FALLBACK]));

/** Registered mdi icon name for a row's domain; neutral shape if unmapped.
 *  Automation rows pass their ``parentKey`` (the targeted component domain),
 *  so the glyph matches that component (binary_sensor, switch, …). */
export function iconForDomain(domain: string): string {
  return (DOMAIN_ICON[domain] ?? FALLBACK)[0];
}
