name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE (by @$AUTHOR in #$NUMBER)"

exclude-contributors:
  - dependabot
  - dependabot[bot]
  - github-actions
  - github-actions[bot]

categories:
  - title: "⚠ Breaking changes"
    labels:
      - breaking-change

  - title: "🚀 New features"
    labels:
      - new-feature
      - enhancement

  - title: "🐛 Bug fixes"
    labels:
      - bugfix

  - title: "🔄 Refactor"
    labels:
      - refactor

  - title: "📚 Documentation"
    labels:
      - docs

  - title: "🧹 Maintenance"
    labels:
      - maintenance

  - title: "⬆️ Dependencies / CI"
    collapse-after: 5
    labels:
      - dependencies
      - ci

template: |
  $CHANGES


  ## :bow: Contributors

  $CONTRIBUTORS
