/**
 * Generated, repo-owned word list for passphrases (~2k common, unambiguous
 * lowercase words; ~11 bits each → ~44 bits for the default 4-word phrase).
 * Dynamically imported by `passphrase.ts` so it stays out of the entry bundle.
 * Stored as one whitespace-separated string (split at load); order is
 * irrelevant, do not rely on indices.
 */
const RAW = `
abacus acorn acrobat actor adder agate agile alarm album alder alight alley alloy allspice almanac almond alpaca aluminum amber amble amethyst amulet anaconda anchor anchovy anemone angelica angler aniseed ankle anklet ant antelope anthem anvil aphid apple apricot apron aqueduct arbor arch archer arm artist ash ashen aspen aster atoll atom atrium attic author autumn avenue avocet awl awning axe axle axolotl azure babble baboon backpack badger bagel bagpipe baker balcony ballad ballast balloon
banana bangle banister banjo banker banquet barbel barge bark barley barn barnacle barrel barrow basalt baseball basement basil basket bass bassoon basswood bat batten batter battery bauble bay beach beacon beam bean beanie bear beaver bed bee beech beechnut beehive beetle beetroot begonia beige belfry bell belt bench bent berry betony bin bind binder bindweed bingo birch birdbath biscuit bison bisque bit black blanket blaze bleak blenny blind blinker blizzard bloom blossom blotter blouse blue
bluebell bluff blur boa boar board boat bob bobcat bog bold bolt bonfire bonnet bookcase bookmark boom boot borage border borer borough bottle bough boulder bouncy bound bow bowl bowling box boxer brace bracelet bracken bracket bradawl braid bramble branch brass brave brawny bread breaker bream breeze breezy briar bridge bridle bright brill brisk brittle broccoli broker bronze bronzed brooch brook broom broth brow brown brownie brunch brush bubble bubbly bucket buckle bud budgie buffalo buggy
bulb bulrush bumpy bun bundle bungalow bunting buoy burger burgundy burly burnish bus bustle butcher butte butter button buttress buzzard cab cabbage cabin cabinet cable caldera calendar calf caliper calm camel camping campion canary candle canister canoe canopy canter canvas canyon cap cape captain caramel caraway card cardamom cardigan caribou carousel carp carpet carriage carrot carryall cart carton carve cascade cashew cashier cask cassava cast castle cattail cattle cauldron causeway cedar
celery cellar cello century cereal chafer chain chair chalet chalice chalk channel chant char charade charcoal chard chariot charm checker cheek cheerful cheery cheese cheetah chemist cherry chervil chess chest chestnut chickpea chicory chili chime chimney chin chipmunk chipper chirp chisel chive chorus chowder chrome chub chunky churn chutney cicada cinder cinnamon circlet circuit citron city clam clamp clang clarinet clasp clatter clay clean clearing cleaver clerk clever cliff climber climbing
clip cloak cloche clock cloister cloth cloud clove clover cluster clutch coach coal coast coaster coat cobalt cobble cobbler cobbles cobra cockatoo cockle cocoa coconut cod cog cogwheel coil col colander collar collect column comfrey common compass compost confetti conger conker coot copper coppice copse coral cord corduroy corer corn cornet coronet corridor cosy cot cottage cotton couch cougar county cove coyote cozy crab cracker crackle cradle crag crane crate crater crayon cream creek cress
crevasse cricket crimson crisp crochet crocus croon crouch crouton crow crowbar crumble crumpet crupper crust crystal cuckoo cucumber cufflink culvert cumin cup cupboard cupcake cupola curator curb curd curl curlew curling currant current curtain cushion custard cutting cyan cycle cycling cyclist cyclone cymbal cypress dab dabble dace daffodil dahlia daisy dale dancer dapper dapple darn dart dash date dawdle dawn daybreak daylight dazzle dealer decade decanter deck deer delta denim dentist
desert desk dew dial diamond diary dibber dice dill dimple dinghy dingo dish district dive diver diving dock doctor dogwood doll dolphin dome domino donkey doormat doorway dot dough dove dovecote dowel downpour drape draught draw drawer dress dresser dressing drift drill driver drizzle druggist drum duck duffel dugong dulcet dumpling dune dunlin dusk dusky dust duster dustpan eager eagle earring earwig easel eave ebony echo eddy editor eel egret einkorn elbow elder elegant elephant elk elm ember
emerald emmer endive engine engrave envelope epoch equinox era eraser estuary etch evening eyebrow eyelash eyelet fabric faint faithful falcon farmer feast feather feeder felt fen fence fencer fender fennel fern ferret ferry fescue fiddle fig filament file filling finch finger fir firefly firework fishing fist fizz fjord flagon flame flamingo flannel flapjack flare flash flask flea fleece fleet flicker flint float florid flounder flour fluffy flurry flute fly foam fog fold folder foot foothill
footpath ford forehead forenoon forest forester forge fork fortress fountain fox foxglove foyer freckle fresh frigate fringe frittata fritter frog frost froth fuchsia fudge fumarole funnel furnace furrow furze fuzzy gable gadwall gale galleon galley gallop gangway gannet gardener garganey garland garlic garnet gasket gate gateway gather gauge gazebo gazelle gazpacho gear gecko gelato gentle geranium gerbil geyser gibbon ginger giraffe girder girth glacier glad glade glass glaze glazier gleam
gleaming glen glide glimmer glint glisten gloom glossy glove glow glowworm gnat gnocchi goat goblet goby godwit gold golden golf gondola goose gorge gorilla gorse gouge goulash gourd gown graceful granary granite granola graphite grater gravel gravity gravy grayling grebe green grey griddle grill grinder grocer grommet grotto grouper grouse grove guard guava gudgeon guitar gull gully gumdrop guppy gurgle gurnard gust gutter gymnast gypsum haddock hail hake halibut hallway halo halter hamlet
hammer hammock hamper hamster hand handbag handle happy harbor hardy harmony harness harp harrier harvest hasp hasty hat hatch hatchet haw hawk hawthorn haze hazel hazelnut headland healer heap hearth hearty heath heather hedge hedgehog heel helmet hem heron herring hickory hike hiker hiking hill hinge hip hippo hockey hoe hog hold holdall holly honest honey honeydew hoodie hook hoop hop horn hornbill hornet horse hotpot hover hoverfly huddle hull hum humble hurdler hushed hyacinth hyena ibex
ibis ice iceberg iguana impala indigo ingot inkwell inlet instant interval iris iron island islet ivory ivy jack jackal jackdaw jacket jade jaguar jam jar jasper jaw jay jeans jelly jester jet jetty jigsaw joiner jolly journal judge jug juggler jumper jumping junction jungle juniper kale kangaroo katydid kayak kebab keel keen keep keepsake keg kestrel kettle khaki kiln kilt kind kite knapsack knee kneel knife knit knob knot knuckle koala krill kudu lace lacewing ladder ladle ladybird ladybug
lagoon lake lamb lamp lamprey landing lane lanky lantern lapwing larch larder lark latch lather lava lavender lawyer lead leaf lean leap leather ledge ledger leech leek leg lemon lemur lens lentil leopard lettuce lever lichen lilac lilting lily lime limpet linden linen ling linger link linnet lintel lion lithe lively lizard llama loach loaf loam lobby lobster locket locust lodge loft loiter loop lorry lottery louse lovage lovebird lowland loyal lozenge ludo lullaby luminous lumpy lunch lustrous
lute lynx macaroon macaw mace mackerel magenta magician magma magnet magnolia magpie mahogany maize mallard mallet mallow mamba manatee mandolin mango manor mansion manta mantel mantis maple marble march marigold marimba marjoram marker marlin maroon marquee marrow marsh marten martin masher mason mast mattress mauve mayfly meadow meander mechanic medlar meerkat megrim mellow melody melon memento mend merchant mercury meringue merry mesa mesh meter midday midge midnight mill millet millpond
miner mineral minnow minstrel mint mirage mirror mist mite mitt mitten mizzle modest molasses mole molecule moment mongoose monitor monkey monsoon moor moorhen mooring moorland moose mop moraine morel morning mortar mosquito moss moth mottle mould mound mountain mouse mud mudflat muffin mug mulberry mulch mule mullet murmur muscle mushroom mussel mustard muted mutter nail napkin narwhal navy neat neck necklace nectar needle nestbox nestle net netball nettle newt nickel nightjar nimble noodle
noon nostril notch notebook notepad nougat nugget numbat nurse nut nutmeg nutty oak oar oasis oat oatmeal oboe obsidian ocean ocelot ochre octave octopus okra olive omelet omelette onion onyx opal orange orca orchard orchid oregano organ oryx osprey otter outcrop overhang owl oyster paddle paddler paddock pail paint painter palette paling pallid palm pan pancake panda pansy panther pantry papaya paprika parakeet parapet parasol parish parrot parsley parsnip pasta pastry pasture pasty patch
patient patter pavement pavilion pea peach peacock peak pear pearl peat pebble pecan peddler peeler peg pelican pelvis pencil pendant pendulum peony pepper perch pergola period perky pestle petal petunia pewter pheasant piano pickaxe pickle picnic pie pier pig pigeon pike pile pillar pillow pilot pin pine pinecone pink pinnacle pintail pipit piston placid plaice plait plane plank planner plantain plate plateau platinum platter platypus plaza pleat pliers plot plover plucky plum plumber plunge
pochard poet polish polished polite pollack pollen pond pony pool poplar popper poppy porch porridge porter porthole portico possum post pot potato potter pouch prairie praline prance prawn pretzel primrose printer prism privet province prow pruner pudding puffball puffin pulley puma pumice pumpkin punt puppet purple purse puzzle python quail quarter quartz quay quiche quick quiet quill quilt quince quinoa quokka rabbit raccoon radiance radiant radiate radish raffle raft rafter rag ragwort rail
railing rain rainbow raisin rake ramble ranger rapid rapids rasp rat ratchet rattle raven ravine ravioli ray red redpoll redwood reed reef region rein relic relish resin rhino rhizome rhubarb rhythm rib ribbon rice riddle ridge riffle rigging rime ripple risotto river rivet rivulet roach roam roast robe robin robust rock rocket roll rolling roofer rook rookery roost root rope rose rosehip rosemary rosy rotor rowan rowboat rower rowing ruby rucksack rudd rudder ruddy ruffle rug rugby rugged ruler
runner running rush rust rustle rye ryegrass sack saddle saffron sage sail sailboat sailfish sailing sailor saithe salmon salt sand sandal sandbank sandbar sandwich sap sapling sapphire sardine satchel satin sauce saucer saunter savanna savory saw scaffold scallion scallop scamper scarf scarlet scatter scholar schooner sconce scone scorpion scree screw scribe scriber scroll scullery sculpt sculptor scurry scuttle scythe sea seahorse seal season sedge seedbed seedling seesaw sepia sequoia serene
settle sew shad shade shadow shale shallot shallows shape shark shawl shears sheep shelf shepherd shim shimmer shin shingle shiny ship shire shirt shoal shoe shoot shore shorts shoulder shovel shoveler shower shrew shrimp shroud shutter sickle sieve silk silo silt silver sincere singer siskin sizzle skate skater skating skerry sketch skewer skier skiff skiing skillet skimmer skink skip skirt skittle skull slate sledge sleek sleet sleigh slender slide slipper sloe sloop sloth slug sluice slush
smog smooth snack snail snake snapper snipe snow snowdrop snug soap soar soccer sock socket sofa soft soil solder sole solstice sonata soothing sorbet sorghum sorrel souffle sound soup souvenir soybean spade spanner spark sparkle sparkler sparrow spatula speckle spelt spicy spider spin spinach spindle spine spiral spire spit splash sponge spoon spore spray spring sprinkle sprint sprinter sprout spruce spry spume spur squall square squash squid squirrel stable stack stake stalk stamp staple
stapler starfish starling steady steam steel stem stencil steppe stern stew stile stingray stir stirrup stitch stocking stool stoop stork storm stout strainer strait stream streamer stride string stripe stroll stud student sturdy sturgeon suburb suds sugar suitcase sumac summer summit sunburnt sundae sundial sunny sunrise sunset sunshine supper supple surf surfer surfing surge surgeon svelte swallow swamp swan sway sweater swede swell swift swimmer swing swirl swoop sycamore symphony syrup table
tack tagine tailor talisman tan tangy tankard tanker tansy taper taro tarragon tart tasty tawny teacher teal teapot teasel teddy temper tempest temple tench tender tendon tennis tent termite tern thaw thicket thigh thistle thorn thread thrip thrower throwing thrum thrush thumb thunder thyme tiara tick tide tidy tie tiger tiller tilt timer timothy tin tinker tint tit titanium toad toast toaster toe toffee toggle token tomato tongs top topaz topping torch tornado torrent tortoise tote toucan towel
tower town towpath tractor trader train tram tranquil trawler tray treacle trefoil trek trellis trestle triangle trickle trifle trill trim trinket trivet trolley trombone trot trousers trout trowel truck trudge truffle trumpet trunk truss trusty tub tuba tuber tuck tulip tumble tuna tundra tunic turbine turbot tureen turkey turmeric turnip turnover turret turtle tutor tweed tweet twig twilight twine twinkle twirl twist ukulele umber umbrella upland urchin valise valley valve van vanilla vapour
vase vat vault veil velvet vendor veranda verse vest vetch viaduct vice villa village vinegar vineyard viola violet violin viper volcano voltage wade waffle wagon wagtail wallaby wallet walnut walrus wander warble warbler ward wardrobe warm washer wasp watch watering wave wavelet wax weasel weave weaver wedge weekday weever weevil weir weld welder wetland whale wharf wheat wheel whelk whey whin whirl whisk whisper whistle white whiting whittle wick widgeon willow wind windmill winter wire wiry
wise witty wolf wombat wonton woodland woodworm wool workshop worm wrap wrasse wren wrench wrestler wrist writer yacht yam yarn yarrow yellow yew yogurt yoyo zebra zephyr zester zesty zinc zinnia zip zipper
`;

/** The de-duplicated passphrase word list. */
export const PASSPHRASE_WORDS: readonly string[] = RAW.split(/\s+/).filter(Boolean);
