import { describe, expect, it } from "vitest";
import {
  categoryChipLabel,
  shouldShowCategoryChip,
} from "../../../src/components/device/component-card-category-label.js";

describe("categoryChipLabel", () => {
  it("title-cases a single-token category id", () => {
    expect(categoryChipLabel("sensor")).toBe("Sensor");
    expect(categoryChipLabel("switch")).toBe("Switch");
    expect(categoryChipLabel("light")).toBe("Light");
  });

  it("splits underscored ids into spaced words", () => {
    // Disambiguating ``sensor.debug`` vs ``text_sensor.debug``
    // is the load-bearing case from device-builder#418 — pin
    // it specifically so a regression that drops the
    // underscore split fails on the user-facing string the
    // chip surfaces.
    expect(categoryChipLabel("text_sensor")).toBe("Text Sensor");
    expect(categoryChipLabel("binary_sensor")).toBe("Binary Sensor");
    expect(categoryChipLabel("media_player")).toBe("Media Player");
    expect(categoryChipLabel("alarm_control_panel")).toBe("Alarm Control Panel");
  });

  it("uppercases known acronyms", () => {
    // ``ota``, ``adc``, ``dac`` are tokens that show up inside
    // category ids today and would render as "Ota" / "Adc" /
    // "Dac" without the acronym table. The set is deliberately
    // tiny — only what current category ids contain — so the
    // maintenance cost stays bounded.
    expect(categoryChipLabel("ota")).toBe("OTA");
    expect(categoryChipLabel("audio_adc")).toBe("Audio ADC");
    expect(categoryChipLabel("audio_dac")).toBe("Audio DAC");
  });

  it("returns an empty string for an empty id", () => {
    // Defensive: the catalog API contract guarantees a
    // non-empty ``category`` field, but if a future schema
    // shift slips something through, an empty chip is
    // friendlier than a crash.
    expect(categoryChipLabel("")).toBe("");
  });

  it("ignores leading / trailing / repeated underscores", () => {
    // The category ids generated by the sync script don't have
    // edge underscores today, but the title-case loop should
    // tolerate them rather than emit empty word slots.
    expect(categoryChipLabel("_sensor")).toBe("Sensor");
    expect(categoryChipLabel("sensor_")).toBe("Sensor");
    expect(categoryChipLabel("sensor__platform")).toBe("Sensor Platform");
  });
});

describe("shouldShowCategoryChip", () => {
  it("shows the chip under the All filter", () => {
    // Every card in the All result set might be from a
    // different category, so the disambiguator earns its
    // place.
    expect(shouldShowCategoryChip("all")).toBe(true);
  });

  it("shows the chip under the Recommended (featured) filter", () => {
    // Featured cards are surfaced from heterogeneous real
    // categories (a featured sensor + a featured switch +
    // ...), so the chip still earns its place when the user
    // is on the Recommended row.
    expect(shouldShowCategoryChip("featured")).toBe(true);
  });

  it("hides the chip when narrowed to a specific category", () => {
    // Once the user has clicked into a single-category view
    // every visible card carries the same category, so the
    // chip is just noise. Pin a representative sample so a
    // regression that flipped the predicate (e.g. defaulting
    // to "show always") would fail loudly.
    expect(shouldShowCategoryChip("sensor")).toBe(false);
    expect(shouldShowCategoryChip("binary_sensor")).toBe(false);
    expect(shouldShowCategoryChip("text_sensor")).toBe(false);
    expect(shouldShowCategoryChip("switch")).toBe(false);
    expect(shouldShowCategoryChip("misc")).toBe(false);
  });
});
